kind: "CDN"
version: "1"
metadata:
  envTypes: ["dev", "stage", "prod"]
data:
  redirects:
    rules:
      - name: redirect-example
        when:
          reqProperty: path
          equals: "/us/gaming-dt.html"
        action:
          type: redirect
          status: 302
          location: /en/products/desktop.html
